import React from "react";
import { useState, useEffect } from "react";
import { Content } from "./index.style";
import MainCalendar from "../../MainCalendar/MainCalendar";
import Dashboard from "../../Dashboard/Dashboard";
import Todolist from "../../Todolist/Todolist";
import Workspace from "../../Workspace/Workspace";
import eventData from "../../../data/events";
import userData from "../../../data/users";

const Main = ({ tab }) => {
  const [id, setId] = useState(500);
  const [toDoData, setToDoData] = useState([
    {
      id: 1,
      title: "HTML",
      name_img: "html.png",
      assignee: "You",
      assignee_img: "thu_1.png",
      description: "Study arrow function",
      duration: {
        day: "",
        hour: "",
        minute: "",
      },
      deadline: new Date(2023, 6, 25, 3, 30),
      percent: "70",
      level: "Critical",
      comple: "false",
      eventType: "todo",
    },
    {
      id: 2,
      title: "SE Project",
      name_img: "se_2.jpg",
      assignee: "Team SE",
      assignee_img: "se_1.jpg",
      description: "Draw Diagram",
      duration: {
        day: "",
        hour: "",
        minute: "",
      },
      deadline: new Date(2023, 6, 12, 5, 0),
      percent: "50",
      level: "Critical",
      comple: "false",
      eventType: "todo",
    },
    {
      id: 3,
      title: "UI UX",
      name_img: "uiux.png",
      assignee: "T2 Team",
      assignee_img: "t2.jpg",
      description: "Coding Homepage",
      duration: {
        day: "",
        hour: "",
        minute: "",
      },
      deadline: new Date(2023, 9, 30, 9, 30),
      percent: "40",
      level: "Low",
      comple: "false",
      eventType: "todo",
    },
    {
      id: 4,
      title: "Figma",
      name_img: "figma.png",
      assignee: "Team design",
      assignee_img: "design_1.webp",
      description: "Design Figma",
      duration: {
        day: "",
        hour: "",
        minute: "",
      },
      deadline: new Date(2023, 7, 1, 7, 0),
      percent: "30",
      level: "Medium",
      comple: "false",
      eventType: "todo",
    },
    {
      id: 5,
      title: "Java",
      name_img: "java.png",
      assignee: "You",
      assignee_img: "thu_1.png",
      description: "Design MVC Model",
      duration: {
        day: "",
        hour: "",
        minute: "",
      },
      deadline: new Date(2023, 6, 16, 20, 30),
      percent: "90",
      level: "High",
      comple: "false",
      eventType: "todo",
    },
    {
      id: 6,
      title: "Python",
      name_img: "python.jpg",
      assignee: "You",
      assignee_img: "thu_1.png",
      description: "ML research",
      duration: {
        day: "",
        hour: "",
        minute: "",
      },
      deadline: new Date(2023, 6, 25, 13, 30),
      percent: "20",
      level: "Medium",
      comple: "false",
      eventType: "todo",
    },
    {
      id: 7,
      title: "HTML",
      name_img: "html.png",
      assignee: "You",
      assignee_img: "thu_1.png",
      description: "Complete the code",
      duration: {
        day: "",
        hour: "",
        minute: "",
      },
      deadline: new Date(2023, 6, 29, 19, 30),
      percent: "80",
      level: "Critical",
      comple: "false",
      eventType: "todo",
    },
    {
      id: 8,
      title: "Database",
      name_img: "database.png",
      assignee: "You",
      assignee_img: "thu_1.png",
      description: "Update database",
      duration: {
        day: "",
        hour: "",
        minute: "",
      },
      deadline: new Date(2023, 6, 13, 21, 0),
      percent: "10",
      level: "Optional",
      comple: "false",
      eventType: "todo",
    },
  ]);

  const [people, setPeople] = useState(userData);

  const [workspaces, setWorkspaces] = useState([
    {
      id: 1,
      avatar: "thu_1.png",
      name: "Việt Nhật 03",
      link: "https://meet.google.com/trc-wnzm-hra",
      todolist: [
        {
          id: 1,
          memberName: "Thu thút",
          memberAvatar: "thu_1.png",
          pjName: "React",
          pjImg: "react.png",
          description: "Coding Homepage",
          deadline: new Date(2023, 6, 17, 17, 30),
          percent: "20",
          level: "Medium",
          comple: "false",
          status: "doing",
          comment: "",
        },
        {
          id: 2,
          memberName: "Bá Hoàng",
          memberAvatar: "python.jpg",
          pjName: "React",
          pjImg: "react.png",
          description: "Coding Login/Sign up",
          deadline: new Date(2023, 6, 9, 21, 30),
          percent: "100",
          level: "Medium",
          comple: "false",
          status: "done",
          comment: "",
        },
        {
          id: 3,
          memberName: "Tuấn Anh",
          memberAvatar: "user6.jpg",
          pjName: "Design",
          pjImg: "figma.png",
          description: "Learning Design Rules",
          deadline: new Date(2023, 6, 15, 22, 0),
          percent: "30",
          level: "High",
          comple: "false",
          status: "doing",
          comment: "",
        },
        {
          id: 4,
          memberName: "Quang Huy",
          memberAvatar: "user5.jpg",
          pjName: "React",
          pjImg: "react.png",
          description: "Coding Layout",
          deadline: new Date(2023, 6, 29, 13, 30),
          percent: "0",
          level: "Medium",
          comple: "false",
          status: "todo",
          comment: "",
        },
        {
          id: 5,
          memberName: "Vũ Hoàng",
          memberAvatar: "user7.jpg",
          pjName: "JavaScript",
          pjImg: "javascript.png",
          description: "Coding Functions",
          deadline: new Date(2023, 6, 20, 16, 30),
          percent: "50",
          level: "High",
          comple: "false",
          status: "doing",
          comment: "",
        },
        {
          id: 6,
          memberName: "Thu thút",
          memberAvatar: "thu_1.png",
          pjName: "React",
          pjImg: "react.png",
          description: "Coding User profile",
          deadline: new Date(2023, 6, 29, 16, 30),
          percent: "0",
          level: "Low",
          comple: "false",
          status: "todo",
          comment: "",
        },
        {
          id: 7,
          memberName: "Tuấn Anh",
          memberAvatar: "user6.jpg",
          pjName: "PowerPoint",
          pjImg: "ppt.png",
          description: "Preparing Slides",
          deadline: new Date(2023, 6, 20, 16, 30),
          percent: "0",
          level: "Low",
          comple: "false",
          status: "todo",
          comment: "",
        },
        {
          id: 8,
          memberName: "Quang Huy",
          memberAvatar: "user5.jpg",
          pjName: "Word",
          pjImg: "word.png",
          description: "Writing Report",
          deadline: new Date(2023, 5, 30, 16, 30),
          percent: "100",
          level: "High",
          comple: "false",
          status: "done",
          comment: "",
        },
        {
          id: 9,
          memberName: "Thu thút",
          memberAvatar: "thu_1.png",
          pjName: "Github",
          pjImg: "github.png",
          description: "Creating Git repository",
          deadline: new Date(2023, 6, 7, 19, 30),
          percent: "100",
          level: "Medium",
          comple: "false",
          status: "done",
          comment: "Good",
        },
        {
          id: 10,
          memberName: "Bá Hoàng",
          memberAvatar: "python.jpg",
          pjName: "React",
          pjImg: "react.png",
          description: "Coding Navbar",
          deadline: new Date(2023, 6, 18, 12, 30),
          percent: "70",
          level: "High",
          comple: "false",
          status: "doing",
          comment: "",
        },
        {
          id: 11,
          memberName: "Vũ Hoàng",
          memberAvatar: "user7.jpg",
          pjName: "Python",
          pjImg: "python.jpg",
          description: "Retrieving Data",
          deadline: new Date(2023, 6, 23, 9, 0),
          percent: "0",
          level: "Medium",
          comple: "false",
          status: "todo",
          comment: "",
        },
        {
          id: 12,
          memberName: "Tuấn Anh",
          memberAvatar: "user6.jpg",
          pjName: "Python",
          pjImg: "python.jpg",
          description: "Cleaning Data",
          deadline: new Date(2023, 6, 24, 18, 0),
          percent: "0",
          level: "Optional",
          comple: "false",
          status: "todo",
          comment: "",
        },
        {
          id: 13,
          memberName: "Quang Huy",
          memberAvatar: "user5.jpg",
          pjName: "JavaScript",
          pjImg: "javascript.png",
          description: "Learning Algorithms",
          deadline: new Date(2023, 6, 17, 9, 0),
          percent: "40",
          level: "Critical",
          comple: "false",
          status: "doing",
          comment: "",
        },
      ],

      teamMems: [
        {
          id: 1,
          memberName: "Thu thút",
          memberAvatar: "thu_1.png",
        },
        {
          id: 2,
          memberName: "Bá Hoàng",
          memberAvatar: "python.jpg",
        },
        {
          id: 3,
          memberName: "Tuấn Anh",
          memberAvatar: "user6.jpg",
        },
        {
          id: 4,
          memberName: "Quang Huy",
          memberAvatar: "user5.jpg",
        },
        {
          id: 5,
          memberName: "Vũ Hoàng",
          memberAvatar: "user7.jpg",
        },
      ],
      team: [
        {
          id: 1,
          name: "Team UIUX",
        },
        {
          id: 2,
          name: "Team AI",
        },
        {
          id: 3,
          name: "Team ITSS",
        },
        {
          id: 4,
          name: "Team Kĩ năng mềm",
        },
        {
          id: 5,
          name: "Team Thuật toán",
        },
      ],
    },
    {
      id: 2,
      avatar: "database.png",
      name: "ĐH Bách khoa",
      link: "https://meet.google.com/dsg-sgrs-dfg",
      todolist: [
        {
          id: 1,
          memberName: "Thu thút",
          memberAvatar: "thu_1.png",
          pjName: "UI UX",
          pjImg: "uiux.png",
          description: "Design home page",
          deadline: new Date(2023, 6, 21, 22, 0),
          percent: "80",
          level: "Optional",
          comple: "false",
          status: "doing",
        },
        {
          id: 2,
          memberName: "Bá Hoàng",
          memberAvatar: "python.jpg",
          pjName: "UI UX",
          pjImg: "uiux.png",
          description: "Design tour page",
          deadline: new Date(2023, 6, 25, 15, 0),
          percent: "0",
          level: "Low",
          comple: "false",
          status: "todo",
        },
        {
          id: 3,
          memberName: "Tuấn Anh",
          memberAvatar: "user6.jpg",
          pjName: "UI UX",
          pjImg: "uiux.png",
          description: "Design address page",
          deadline: new Date(2023, 6, 25, 19, 0),
          percent: "40",
          level: "High",
          comple: "false",
          status: "doing",
        },
        {
          id: 4,
          memberName: "Quang Huy",
          memberAvatar: "user5.jpg",
          pjName: "UI UX",
          pjImg: "uiux.png",
          description: "Design manager page",
          deadline: new Date(2023, 5, 26, 9, 30),
          percent: "100",
          level: "Optional",
          comple: "false",
          status: "done",
        },
        {
          id: 5,
          memberName: "Vũ Hoàng",
          memberAvatar: "user7.jpg",
          pjName: "UI UX",
          pjImg: "uiux.png",
          description: "Design admin page",
          deadline: new Date(2023, 6, 26, 10, 0),
          percent: "0",
          level: "Low",
          comple: "false",
          status: "todo",
        },
      ],
      teamMems: [
        {
          id: 1,
          memberName: "Thu thút",
          memberAvatar: "thu_1.png",
        },
        {
          id: 2,
          memberName: "Bá Hoàng",
          memberAvatar: "python.jpg",
        },
        {
          id: 3,
          memberName: "Tuấn Anh",
          memberAvatar: "user6.jpg",
        },
        {
          id: 4,
          memberName: "Quang Huy",
          memberAvatar: "user5.jpg",
        },
        {
          id: 5,
          memberName: "Vũ Hoàng",
          memberAvatar: "user7.jpg",
        },
      ],
      team: [
        {
          id: 1,
          name: "Team Toán cao cấp",
        },
        {
          id: 2,
          name: "Team Vật lý",
        },
        {
          id: 3,
          name: "Team Pháp luật",
        },
        {
          id: 4,
          name: "Team Hóa",
        },
        {
          id: 5,
          name: "Team Quân sự",
        },
      ],
    },
    {
      id: 3,
      avatar: "design_1.webp",
      name: "Sun* Asterisk",
      link: "https://meet.google.com/ats-gstj-lpa",
      todolist: [
        {
          id: 1,
          memberName: "Thu thút",
          memberAvatar: "thu_1.png",
          pjName: "Java",
          pjImg: "java.png",
          description: "Design MVC Model",
          deadline: new Date(2023, 6, 28, 17, 30),
          percent: "60",
          level: "Critical",
          comple: "false",
          status: "doing",
        },

        {
          id: 2,
          memberName: "Bá Hoàng",
          memberAvatar: "python.jpg",
          pjName: "Java",
          pjImg: "java.png",
          description: "Design usecase",
          deadline: new Date(2023, 6, 28, 21, 0),
          percent: "0",
          level: "Critical",
          comple: "false",
          status: "todo",
        },
        {
          id: 3,
          memberName: "Tuấn Anh",
          memberAvatar: "user6.jpg",
          pjName: "Java",
          pjImg: "java.png",
          description: "Design Admin frame",
          deadline: new Date(2023, 5, 30, 15, 0),
          percent: "100",
          level: "Low",
          comple: "false",
          status: "done",
        },
        {
          id: 4,
          memberName: "Quang Huy",
          memberAvatar: "user5.jpg",
          pjName: "Java",
          pjImg: "java.png",
          description: "Design Manager frame",
          deadline: new Date(2023, 6, 1, 21, 30),
          percent: "100",
          level: "Low",
          comple: "false",
          status: "done",
        },
        {
          id: 5,
          memberName: "Vũ Hoàng",
          memberAvatar: "user7.jpg",
          pjName: "Java",
          pjImg: "java.png",
          description: "Design Tour frame",
          deadline: new Date(2023, 6, 20, 7, 30),
          percent: "50",
          level: "Medium",
          comple: "false",
          status: "doing",
        },
        {
          id: 6,
          memberName: "Huy Hoàng",
          memberAvatar: "user3.jpg",
          pjName: "Java",
          pjImg: "java.png",
          description: "Coding Login/Register",
          deadline: new Date(2023, 6, 23, 12, 30),
          percent: "80",
          level: "Optional",
          comple: "false",
          status: "doing",
        },
        {
          id: 7,
          memberName: "Hào Quang",
          memberAvatar: "user2.jpg",
          pjName: "Java",
          pjImg: "java.png",
          description: "Coding Tour frame",
          deadline: new Date(2023, 6, 30, 7, 30),
          percent: "0",
          level: "Medium",
          comple: "false",
          status: "todo",
        },
        {
          id: 8,
          memberName: "Minh Quang",
          memberAvatar: "user1.jpg",
          pjName: "Java",
          pjImg: "java.png",
          description: "Coding Home page",
          deadline: new Date(2023, 6, 13, 8, 30),
          percent: "90",
          level: "Low",
          comple: "false",
          status: "doing",
        },
      ],
      teamMems: [
        {
          id: 1,
          memberName: "Thu thút",
          memberAvatar: "thu_1.png",
        },

        {
          id: 2,
          memberName: "Bá Hoàng",
          memberAvatar: "python.jpg",
        },
        {
          id: 3,
          memberName: "Tuấn Anh",
          memberAvatar: "user6.jpg",
        },
        {
          id: 4,
          memberName: "Quang Huy",
          memberAvatar: "user5.jpg",
        },
        {
          id: 5,
          memberName: "Vũ Hoàng",
          memberAvatar: "user7.jpg",
        },
        {
          id: 6,
          memberName: "Huy Hoàng",
          memberAvatar: "user3.jpg",
        },
        {
          id: 7,
          memberName: "Hào Quang",
          memberAvatar: "user2.jpg",
        },
        {
          id: 8,
          memberName: "Minh Quang",
          memberAvatar: "user1.jpg",
        },
      ],
      team: [
        {
          id: 1,
          name: "Team TC",
        },
        {
          id: 2,
          name: "Team Naitei",
        },
        {
          id: 3,
          name: "Team N2",
        },
        {
          id: 4,
          name: "Team Văn hóa",
        },
        {
          id: 5,
          name: "Team Tuyển dụng",
        },
      ],
    },
    {
      id: 4,
      avatar: "se_2.jpg",
      name: "Nghiên cứu tốt nghiệp",
      link: "https://meet.google.com/mvx-tyio-ter",
      todolist: [
        {
          id: 1,
          memberName: "Thu thút",
          memberAvatar: "thu_1.png",
          pjName: "Database",
          pjImg: "database.png",
          description: "Create Admin table",
          deadline: new Date(2023, 6, 23, 9, 30),
          percent: "50",
          level: "Optional",
          comple: "false",
          status: "doing",
        },
        {
          id: 2,
          memberName: "Bá Hoàng",
          memberAvatar: "python.jpg",
          pjName: "Database",
          pjImg: "database.png",
          description: "Create Manager table",
          deadline: new Date(2023, 6, 23, 13, 30),
          percent: "80",
          level: "Low",
          comple: "false",
          status: "doing",
        },
        {
          id: 3,
          memberName: "Tuấn Anh",
          memberAvatar: "user6.jpg",
          pjName: "Database",
          pjImg: "database.png",
          description: "Create Tour table",
          deadline: new Date(2023, 6, 3, 17, 30),
          percent: "100",
          level: "High",
          comple: "false",
          status: "done",
        },
        {
          id: 4,
          memberName: "Quang Huy",
          memberAvatar: "user5.jpg",
          pjName: "Database",
          pjImg: "database.png",
          description: "Create Address table",
          deadline: new Date(2023, 6, 30, 20, 30),
          percent: "0",
          level: "Medium",
          comple: "false",
          status: "todo",
        },
      ],
      teamMems: [
        {
          id: 1,
          memberName: "Thu thút",
          memberAvatar: "thu_1.png",
        },
        {
          id: 2,
          memberName: "Bá Hoàng",
          memberAvatar: "python.jpg",
        },
        {
          id: 3,
          memberName: "Tuấn Anh",
          memberAvatar: "user6.jpg",
        },
        {
          id: 4,
          memberName: "Quang Huy",
          memberAvatar: "user5.jpg",
        },
      ],
      team: [
        {
          id: 1,
          name: "Team GR1",
        },
        {
          id: 2,
          name: "Team GR2",
        },
        {
          id: 3,
          name: "Team GR3",
        },
        {
          id: 4,
          name: "Team Lab",
        },
        {
          id: 5,
          name: "Team Tốt nghiệp",
        },
      ],
    },
  ]);

  const [workspacesToJoin, setWorkspacesToJoin] = useState([
    {
      id: 5,
      avatar: "thu_1.png",
      name: "Công ty Vui vẻ",
      teamMems: [
        {
          id: 1,
          memberName: "Thu thút",
          memberAvatar: "thu_1.png",
          pjName: "Python",
          pjImg: "python.jpg",
          description: "Coding Homepage",
          deadline: new Date(2023, 6, 3, 8, 30),
          percent: "20",
          level: "Medium",
          comple: "false",
        },
        {
          id: 2,
          memberName: "Bá Hoàng",
          memberAvatar: "python.jpg",
          pjName: "Python",
          pjImg: "python.jpg",
          description: "Coding Login/Sign up",
          deadline: new Date(2023, 6, 4, 8, 30),
          percent: "60",
          level: "Medium",
          comple: "false",
        },
        {
          id: 3,
          memberName: "Tuấn Anh",
          memberAvatar: "user6.jpg",
          pjName: "Python",
          pjImg: "python.jpg",
          description: "Learning Design Rules",
          deadline: new Date(2023, 6, 5, 8, 30),
          percent: "30",
          level: "High",
          comple: "false",
        },
        {
          id: 4,
          memberName: "Quang Huy",
          memberAvatar: "user5.jpg",
          pjName: "Python",
          pjImg: "python.jpg",
          description: "Coding Layout",
          deadline: new Date(2023, 5, 21, 8, 30),
          percent: "80",
          level: "Low",
          comple: "false",
        },
      ],
    },
    {
      id: 6,
      avatar: "database.png",
      name: "Quản lý Số",
      teamMems: [
        {
          id: 1,
          memberName: "Thu thút",
          memberAvatar: "thu_1.png",
          pjName: "UI UX",
          pjImg: "uiux.png",
          description: "Design home page",
          deadline: new Date(2023, 5, 22, 8, 30),
          percent: "80",
          level: "Optional",
          comple: "false",
        },
        {
          id: 2,
          memberName: "Bá Hoàng",
          memberAvatar: "python.jpg",
          pjName: "UI UX",
          pjImg: "uiux.png",
          description: "Design tour page",
          deadline: new Date(2023, 5, 21, 20, 30),
          percent: "50",
          level: "Low",
          comple: "false",
        },
        {
          id: 3,
          memberName: "Tuấn Anh",
          memberAvatar: "user6.jpg",
          pjName: "UI UX",
          pjImg: "uiux.png",
          description: "Design address page",
          deadline: new Date(2023, 5, 22, 20, 30),
          percent: "40",
          level: "High",
          comple: "false",
        },
        {
          id: 4,
          memberName: "Quang Huy",
          memberAvatar: "user5.jpg",
          pjName: "UI UX",
          pjImg: "uiux.png",
          description: "Design manager page",
          deadline: new Date(2023, 5, 23, 20, 30),
          percent: "90",
          level: "Optional",
          comple: "false",
        },
        {
          id: 5,
          memberName: "Vũ Hoàng",
          memberAvatar: "user7.jpg",
          pjName: "UI UX",
          pjImg: "uiux.png",
          description: "Design admin page",
          deadline: new Date(2023, 5, 24, 20, 30),
          percent: "60",
          level: "Low",
          comple: "false",
        },
      ],
    },
    {
      id: 7,
      avatar: "design_1.webp",
      name: "Dự án thiết kế",
      teamMems: [
        {
          id: 1,
          memberName: "Thu thút",
          memberAvatar: "thu_1.png",
          pjName: "Java",
          pjImg: "java.png",
          description: "Design MVC Model",
          deadline: new Date(2023, 5, 25, 20, 30),
          percent: "60",
          level: "Critical",
          comple: "false",
        },

        {
          id: 2,
          memberName: "Bá Hoàng",
          memberAvatar: "python.jpg",
          pjName: "Java",
          pjImg: "java.png",
          description: "Design usecase",
          deadline: new Date(2023, 5, 30, 20, 30),
          percent: "60",
          level: "Critical",
          comple: "false",
        },
        {
          id: 3,
          memberName: "Tuấn Anh",
          memberAvatar: "user6.jpg",
          pjName: "Java",
          pjImg: "java.png",
          description: "Design Admin frame",
          deadline: new Date(2023, 5, 25, 20, 30),
          percent: "40",
          level: "Low",
          comple: "false",
        },
        {
          id: 4,
          memberName: "Quang Huy",
          memberAvatar: "user5.jpg",
          pjName: "Java",
          pjImg: "java.png",
          description: "Design Manager frame",
          deadline: new Date(2023, 5, 27, 20, 30),
          percent: "30",
          level: "Low",
          comple: "false",
        },
        {
          id: 5,
          memberName: "Vũ Hoàng",
          memberAvatar: "user7.jpg",
          pjName: "Java",
          pjImg: "java.png",
          description: "Design Tour frame",
          deadline: new Date(2023, 5, 28, 20, 30),
          percent: "50",
          level: "Medium",
          comple: "false",
        },
        {
          id: 6,
          memberName: "Huy Hoàng",
          memberAvatar: "user3.jpg",
          pjName: "Java",
          pjImg: "java.png",
          description: "Coding Login/Register",
          deadline: new Date(2023, 5, 30, 20, 30),
          percent: "80",
          level: "Optional",
          comple: "false",
        },
        {
          id: 7,
          memberName: "Hào Quang",
          memberAvatar: "user2.jpg",
          pjName: "Java",
          pjImg: "java.png",
          description: "Coding Tour frame",
          deadline: new Date(2023, 5, 30, 13, 30),
          percent: "20",
          level: "Medium",
          comple: "false",
        },
        {
          id: 8,
          memberName: "Minh Quang",
          memberAvatar: "user1.jpg",
          pjName: "Java",
          pjImg: "java.png",
          description: "Coding Home page",
          deadline: new Date(2023, 5, 30, 17, 30),
          percent: "90",
          level: "Low",
          comple: "false",
        },
      ],
    },
    {
      id: 8,
      avatar: "se_2.jpg",
      name: "AI Project",
      teamMems: [
        {
          id: 1,
          memberName: "Thu thút",
          memberAvatar: "thu_1.png",
          pjName: "Database",
          pjImg: "database.png",
          description: "Create Admin table",
          deadline: new Date(2023, 6, 1, 13, 30),
          percent: "50",
          level: "Optional",
          comple: "false",
        },
        {
          id: 2,
          memberName: "Bá Hoàng",
          memberAvatar: "python.jpg",
          pjName: "Database",
          pjImg: "database.png",
          description: "Create Manager table",
          deadline: new Date(2023, 5, 25, 13, 0),
          percent: "80",
          level: "Low",
          comple: "false",
        },
        {
          id: 3,
          memberName: "Tuấn Anh",
          memberAvatar: "user6.jpg",
          pjName: "Database",
          pjImg: "database.png",
          description: "Create Tour table",
          deadline: new Date(2023, 5, 29, 13, 0),
          percent: "90",
          level: "High",
          comple: "false",
        },
        {
          id: 4,
          memberName: "Quang Huy",
          memberAvatar: "user5.jpg",
          pjName: "Database",
          pjImg: "database.png",
          description: "Create Address table",
          deadline: new Date(2023, 5, 30, 13, 0),
          percent: "70",
          level: "Medium",
          comple: "false",
        },
      ],
    },
  ]);
  const [events, setEvents] = useState(
    eventData.map((event) => {
      if (event.start.split === undefined) return event;
      let newEvent = event;

      newEvent.start = new Date(
        event.start.split("/")[0],
        event.start.split("/")[1],
        event.start.split("/")[2],
        event.start.split("/")[3],
        event.start.split("/")[4]
      );
      newEvent.start = new Date(
        newEvent.start.getTime() + 60 * 60 * 1000 * 24 * 14
      );

      newEvent.end = new Date(
        event.end.split("/")[0],
        event.end.split("/")[1],
        event.end.split("/")[2],
        event.end.split("/")[3],
        event.end.split("/")[4]
      );
      newEvent.end = new Date(
        newEvent.end.getTime() + 60 * 60 * 1000 * 24 * 14
      );
      return newEvent;
    })
  );

  return (
    <Content>
      {/* {tab === "dashboard" && <Dashboard />} */}
      {tab === "calendar" && (
        <MainCalendar
          events={events}
          setEvents={setEvents}
          id={id}
          setId={setId}
          toDoData={toDoData}
          setToDoData={setToDoData}
        />
      )}
      {tab === "todolist" && (
        <Todolist
          id={id}
          setId={setId}
          toDoData={toDoData}
          setToDoData={setToDoData}
          events={events}
          setEvents={setEvents}
        />
      )}
      {tab === "workspace" && (
        <Workspace
          id={id}
          setId={setId}
          workspaces={workspaces}
          setWorkspaces={setWorkspaces}
          workspacesToJoin={workspacesToJoin}
          setWorkspacesToJoin={setWorkspacesToJoin}
          people={people}
          toDoData={toDoData}
          setToDoData={setToDoData}
        />
      )}
    </Content>
  );
};

export default Main;
